stages:
  - initialize
  - test
  - build
  - release
  - publish

cache:
  paths:
    - node_modules/

initialize-build:
  stage: initialize
  script:
    - npm i

test-proxy:
  stage: test
  script:
    - sh clean-up.sh
    - npm run test
    - sh clean-up.sh

build-proxy:
  stage: build
  script:
    - npm run build
